name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: '*/30 * * * *'
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          plugin_introduction: no
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_limit: 80
          plugin_languages_details: bytes-size, percentage
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}
