name: 🌇 GitHub Skyline 3D calendar

cost: N/A
category: github
index: 23
supports:
  - user
inputs:

  # Enable or disable plugin
  plugin_skyline:
    description: Display GitHub Skyline 3D calendar
    type: boolean
    default: no

  # Displayed year
  plugin_skyline_year:
    description: Displayed year
    type: number
    default: "current-year"
    min: 2008

  # Number of frames
  # Use 120 for a full-loop and 60 for a half-loop
  plugin_skyline_frames:
    description: Number of frames
    type: number
    default: 60
    min: 1
    max: 120

  # Image quality
  plugin_skyline_quality:
    description: Image quality
    type: number
    default: 0.5
    min: 0.1
    max: 1

  # This uses CSS animations instead of GIF to support a wider range of browser like FireFox and Safari
  # Using this mode significantly increase file size as each frame is encoded separately
  plugin_skyline_compatibility:
    description: Compatibility mode
    type: boolean
    default: no